# Generated by Django 5.2.1 on 2025-05-22 06:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='botdownloadactivationlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_activation_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='botfile',
            name='bot_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='api.botdetail'),
        ),
        migrations.AddField(
            model_name='botdownloadactivationlog',
            name='bot_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='download_logs', to='api.botfile'),
        ),
        migrations.AddField(
            model_name='botlicense',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_licenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='botdownloadactivationlog',
            name='bot_license',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activation_logs', to='api.botlicense'),
        ),
        migrations.CreateModel(
            name='DigitalInventory',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='inventory', serialize=False, to='api.product')),
                ('total_stock', models.IntegerField(blank=True, null=True)),
                ('available_stock', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='botlicense',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='api.product'),
        ),
        migrations.AddField(
            model_name='botdetail',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bot_detail', to='api.product'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.order'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='api.product'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_bundle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='api.productbundle'),
        ),
        migrations.AddField(
            model_name='productbundleitem',
            name='bundle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.productbundle'),
        ),
        migrations.AddField(
            model_name='productbundleitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product'),
        ),
        migrations.AddField(
            model_name='productbundle',
            name='products',
            field=models.ManyToManyField(related_name='bundles', through='api.ProductBundleItem', to='api.product'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.productcategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.productcategory'),
        ),
        migrations.AddField(
            model_name='productreview',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.product'),
        ),
        migrations.AddField(
            model_name='productreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productsubscriptionplan',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_plans', to='api.product'),
        ),
        migrations.AddField(
            model_name='signaldetail',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signal_detail', to='api.product'),
        ),
        migrations.AddField(
            model_name='userbotconfiguration',
            name='bot_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_configurations', to='api.product'),
        ),
        migrations.AddField(
            model_name='userbotconfiguration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_configurations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='botlicense',
            name='user_bot_configuration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licenses', to='api.userbotconfiguration'),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='subscription_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_subscriptions', to='api.productsubscriptionplan'),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='productbundleitem',
            unique_together={('bundle', 'product')},
        ),
    ]
